name: Build & Test
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.go'
  pull_request:
    paths:
      - '**/*.go'

jobs:
  build:
    name: Build And Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.22, 1.23]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Upload Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          fail_ci_if_error: true
          verbose: true
